easy_admin:
    entities:
        Post:
            class: App\Entity\Post
        Category:
            class: App\Entity\Category
        Tag:
            class: App\Entity\Tag

    site_name: 'My adminPanel' 